# This Workflow is used to Validate AWS Credentials. 
# 
# To use this workflow, you must configure the following GHA Secrets:
# AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
# in two environments: dev and prod
#
# and then run the workflow from the UI
# 

name: 00 Validate AWS credentials
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: true
        type: environment

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        
    - name: Get AWS Account Number
      run: echo "AWS_ACCOUNT_NUMBER=$(aws sts get-caller-identity --query 'Account' --output text)" >> $GITHUB_ENV
        
    - name: Message
      run: echo "AWS Credentials are valid for the account ${{ env.AWS_ACCOUNT_NUMBER }}"
        
    - name: Account Name
      run: aws sts get-caller-identity --query 'Arn' --output text
