# This Workflow is used to check the App NodeJS when PR 
# 
# To use this workflow, you must configure the following GHA Secrets:
# AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, NEW_RELIC_LICENSE_KEY
# in two environments: dev and prod
#
# and then run the workflow from the UI
# 

name: Pull Request App
on:
  pull_request:
    branches:
      - main
    paths:
      - "app/*"
      - ".github/workflows/pull_request_app.yml"

env:
  AWS_DEFAULT_REGION: us-east-1
  CLUSTER_NAME: cluster-app-dev
  SERVICE_NAME: app01-dev

jobs:
  deploy:
    name: Validate PR
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
        
    - name: Build
      run: |
        cd app
        docker build -t app01-dev --build-arg NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }} .

    - name: Run tests
      run: |
        echo "Running tests...."
  