# This Workflow is used to provision a S3 bucket for Terraform State. 
# 
# To use this workflow, you must configure the following GHA Secrets:
# AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
# in two environments: dev and prod
#
# and then run the workflow from the UI or just change the code in specific places
# see below the path filters
# 

name: 01 S3 Bucket for TF
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      environment:
        description: 'Environment'     
        required: true
        type: string


  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: true
        type: environment

  push:
    branches:
      - main
    paths:
      - .github/workflows/01-provision-s3-bucket-for-terraform.yml
env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      S3_BUCKET_NAME: goweb-terraform-state-bucket-${{ inputs.environment }}

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Create S3 bucket
      run: |
        aws s3api create-bucket --bucket ${{ env.S3_BUCKET_NAME }}

    - name: S3 bucket encryption
      run: |
        aws s3api put-bucket-encryption \
        --bucket ${{env.S3_BUCKET_NAME}} \
        --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'

    - name: S3 bucket listing
      run: aws s3 ls
